# Generated by Django 6.0.7 on 2026-08-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, help_text="Leave empty when using a unit such as 'To taste'.", max_digits=7, null=True)),
                ('unit', models.CharField(choices=[('g', 'g'), ('kg', 'kg'), ('ml', 'ml'), ('l', 'l'), ('tsp', 'tsp'), ('tbsp', 'tbsp'), ('cup', 'cup'), ('piece', 'piece'), ('slice', 'slice'), ('clove', 'clove'), ('can', 'can'), ('to_taste', 'To taste')], max_length=20)),
                ('preparation_note', models.CharField(blank=True, help_text='Optional, for example: chopped or finely sliced.', max_length=150)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='recipes.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='recipes.recipe')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('recipe', 'ingredient'), name='unique_ingredient_per_recipe')],
            },
        ),
    ]
